site_name: "clusterProfiler"
site_url: https://guangchuangyu.github.io/clusterProfiler
site_author: Guangchuang Yu
repo_url: https://github.com/GuangchuangYu/clusterProfiler
site_dir: ../docs
theme: yeti
pages:
- Home: index.md
- Documentation: documentation.md
- Featured Articles: featuredArticles.md
- My Software:
  - ChIPseeker: ChIPseeker.md
  - clusterProfiler: clusterProfiler.md
  - DOSE: DOSE.md
  - ggtree: ggtree.md
  - GOSemSim: GOSemSim.md
  - meshes: meshes.md
  - ReactomePA: ReactomePA.md


copyright: Copyright &copy; 2016 <a href="https://guangchuangyu.github.io">Guangchuang Yu</a>.<div style="width:250px;margin:auto;"><script type="text/javascript" src="//rf.revolvermaps.com/0/0/7.js?i=5qpvv5zz7fp&amp;m=0&amp;c=ff0000&amp;cr1=ffffff&amp;sx=0" async="async"></script></div>

